---
repos:
  - repo: https://github.com/ambv/black
    # This warns:
    # DEPRECATION: Python 2 support will be removed in the first stable release
    # expected in January 2022.
    # And indeed 22.1.0 dropped support for py27
    rev: 21.12b0
    hooks:
    - id: black
      language_version: python3
      additional_dependencies: [click==8.0.4]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: flake8
        additional_dependencies: [
          flake8-logging-format,
        ]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
